"use client";

import { useState, useRef} from "react";
import {
  X,
  Loader2,
  Camera,
  Sparkles,
  Clock,
  Star,
  CheckCircle2,
  Compass,
  Plus,
  HelpCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import {
  ACTIVITY_TEMPLATES,
  ActivityTemplate,
} from "@/lib/activity-templates";

// ─── Constants ────────────────────────────────────────────────────────────────

const SUBJECTS = [
  { label: "Maths",            emoji: "🔢" },
  { label: "English",          emoji: "📖" },
  { label: "Science",          emoji: "🔬" },
  { label: "Art",              emoji: "🎨" },
  { label: "Geography",        emoji: "🗺️" },
  { label: "Islamic Studies",  emoji: "🌙" },
  { label: "PE",               emoji: "⚽" },
  { label: "Day out",          emoji: "🚗" },
  { label: "History",          emoji: "🏺" },
  { label: "Music",            emoji: "🎵" },
  { label: "Computing",        emoji: "💻" },
  { label: "Other",            emoji: "📝" },
];

const MOMENTS: {
  value: "REGULAR" | "BREAKTHROUGH" | "DAY_OUT" | "CREATIVE" | "SPECIAL";
  label: string;
  emoji: string;
}[] = [
  { value: "REGULAR",     label: "Regular lesson",   emoji: "📚" },
  { value: "BREAKTHROUGH", label: "Breakthrough!",    emoji: "✨" },
  { value: "DAY_OUT",     label: "Day out",           emoji: "🚗" },
  { value: "CREATIVE",    label: "Creative work",     emoji: "🎨" },
  { value: "SPECIAL",     label: "Special memory",    emoji: "⭐" },
];

const DURATION_PRESETS = [15, 30, 45, 60, 90, 120];

// ─── Types ────────────────────────────────────────────────────────────────────

export interface AddEntryModalProps {
  childId: string;
  childName: string;
  /** Pre-select an activity template */
  initialTemplateId?: string;
  /** Pre-fill from lesson completion */
  prefill?: {
    lessonId: string;
    subject: string;
    topic: string;
  };
  onClose: () => void;
  onSaved: () => void;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function AddEntryModal({
  childId,
  childName,
  initialTemplateId,
  prefill,
  onClose,
  onSaved,
}: AddEntryModalProps) {
  const initialTmpl = initialTemplateId
    ? ACTIVITY_TEMPLATES.find((t) => t.id === initialTemplateId)
    : null;

  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(
    initialTmpl?.id ?? null
  );

  const [notes, setNotes] = useState(
    prefill ? `Today we worked on "${prefill.topic}". ` : ""
  );
  const [subject, setSubject] = useState(
    prefill?.subject ?? initialTmpl?.subject ?? ""
  );
  const [title, setTitle] = useState(
    prefill?.topic ?? initialTmpl?.defaultTitle ?? ""
  );
  const [moment, setMoment] = useState(initialTmpl?.moment ?? "REGULAR");
  const [durationMins, setDurationMins] = useState<string>(
    initialTmpl ? String(initialTmpl.defaultDurationMins) : ""
  );
  const [tags, setTags] = useState<string[]>(initialTmpl?.defaultTags ?? []);
  const [entryDate, setEntryDate] = useState(
    new Date().toISOString().split("T")[0]
  );
  const [photoUrl, setPhotoUrl] = useState<string | null>(null);
  const [uploadLoading, setUploadLoading] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [suggestedSkills, setSuggestedSkills] = useState<string[]>([]);
  const [learningSummary, setLearningSummary] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  const activeTemplate = ACTIVITY_TEMPLATES.find(
    (t) => t.id === selectedTemplateId
  );

  // Apply template selection
  function handleSelectTemplate(tmpl: ActivityTemplate | null) {
    if (!tmpl) {
      setSelectedTemplateId(null);
      return;
    }

    setSelectedTemplateId(tmpl.id);

    // Apply template properties cleanly
    setSubject(tmpl.subject);
    setMoment(tmpl.moment);
    setDurationMins(String(tmpl.defaultDurationMins));

    // If current title is empty or was previously generated by another template, update it
    const wasTemplateTitle = ACTIVITY_TEMPLATES.some(
      (t) => t.defaultTitle === title
    );
    if (!title.trim() || wasTemplateTitle) {
      setTitle(tmpl.defaultTitle);
    }

    // Assign default template tags
    setTags(tmpl.defaultTags);
  }

  // Insert guided prompt into notes
  function handleInsertPrompt(promptText: string) {
    const addition = `\n\n• ${promptText}\n  `;
    setNotes((prev) => (prev ? prev.trimEnd() + addition : `• ${promptText}\n  `));
    setTimeout(() => {
      if (textareaRef.current) {
        textareaRef.current.focus();
        textareaRef.current.scrollTop = textareaRef.current.scrollHeight;
      }
    }, 50);
  }

  async function handleAutoAnalyze() {
    if (!notes.trim()) {
      setError("Write a short description or note first so AI can analyse it.");
      return;
    }
    setAnalyzing(true);
    setError("");
    try {
      const res = await fetch("/api/journal/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          notes: notes.trim(),
          childId,
          subject: subject || undefined,
        }),
      });

      if (!res.ok) {
        const d = await res.json().catch(() => ({}));
        throw new Error(d.error || "AI analysis failed");
      }

      const { analysis } = await res.json();
      if (analysis) {
        if (analysis.suggestedTitle && (!title || title.startsWith("Journal entry"))) {
          setTitle(analysis.suggestedTitle);
        }
        if (analysis.suggestedSubject && !subject) {
          const match = SUBJECTS.find(
            (s) => s.label.toLowerCase() === analysis.suggestedSubject.toLowerCase()
          );
          if (match) setSubject(match.label);
        }
        if (analysis.suggestedMoment) {
          setMoment(analysis.suggestedMoment);
        }
        if (Array.isArray(analysis.suggestedTags)) {
          const newTags = analysis.suggestedTags.map((t: string) =>
            t.toLowerCase().trim()
          );
          setTags((prev) => Array.from(new Set([...prev, ...newTags])));
        }
        if (analysis.estimatedDurationMins && !durationMins) {
          setDurationMins(String(analysis.estimatedDurationMins));
        }
        if (Array.isArray(analysis.keySkills)) {
          setSuggestedSkills(analysis.keySkills);
        }
        if (analysis.learningSummary) {
          setLearningSummary(analysis.learningSummary);
        }
      }
    } catch (err: unknown) {
      setError(
        err instanceof Error
          ? err.message
          : "AI analysis was unable to complete."
      );
    } finally {
      setAnalyzing(false);
    }
  }

  async function handlePhotoChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploadLoading(true);
    try {
      const fd = new FormData();
      fd.append("file", file);
      const res = await fetch("/api/journal/upload", {
        method: "POST",
        body: fd,
      });
      if (!res.ok) throw new Error("Upload failed");
      const data = await res.json();
      setPhotoUrl(data.url);
    } catch {
      setError("Photo upload failed. You can still save without a photo.");
    } finally {
      setUploadLoading(false);
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!notes.trim()) {
      setError("Please add a note or description.");
      return;
    }
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/journal", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          childId,
          notes: notes.trim(),
          subject: subject || undefined,
          title: title.trim() || undefined,
          moment,
          lessonId: prefill?.lessonId ?? undefined,
          photoUrl: photoUrl ?? undefined,
          durationMins: durationMins ? parseInt(durationMins, 10) : undefined,
          tags,
          entryDate,
        }),
      });
      if (!res.ok) {
        const d = await res.json().catch(() => ({}));
        throw new Error(d.error ?? "Failed to save");
      }
      onSaved();
      onClose();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/50 p-0 sm:p-4"
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div className="bg-white w-full sm:max-w-xl rounded-t-3xl sm:rounded-2xl max-h-[92vh] overflow-y-auto shadow-2xl">
        {/* Sticky header */}
        <div className="sticky top-0 bg-white/95 backdrop-blur-sm flex items-center justify-between px-5 py-3.5 border-b border-[hsl(var(--border))] rounded-t-3xl sm:rounded-t-2xl z-10">
          <div>
            <h2 className="font-display font-bold text-brand-green-deep">
              {prefill
                ? `Journal note for ${childName}`
                : `Log learning for ${childName}`}
            </h2>
            <p className="text-[11px] text-muted-foreground">
              {activeTemplate
                ? `${activeTemplate.emoji} ${activeTemplate.label}`
                : "Real-world activity, field trip, or lesson reflection"}
            </p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-muted flex items-center justify-center hover:bg-muted/80 transition-colors"
          >
            <X className="w-4 h-4 text-muted-foreground" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="px-5 py-4 space-y-4">
          {/* Template Selector Carousel */}
          {!prefill && (
            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <Label className="text-xs font-semibold text-brand-green-deep uppercase tracking-wider flex items-center gap-1.5">
                  <Compass className="w-3.5 h-3.5 text-brand-green" />
                  <span>Activity Templates</span>
                </Label>
                {selectedTemplateId && (
                  <button
                    type="button"
                    onClick={() => handleSelectTemplate(null)}
                    className="text-[11px] text-muted-foreground hover:text-brand-green hover:underline"
                  >
                    Clear template
                  </button>
                )}
              </div>

              <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none pt-0.5">
                <button
                  type="button"
                  onClick={() => handleSelectTemplate(null)}
                  className={cn(
                    "px-3 py-1.5 rounded-xl border text-xs font-medium shrink-0 transition-all flex items-center gap-1.5",
                    selectedTemplateId === null
                      ? "bg-brand-green text-white border-brand-green shadow-xs"
                      : "bg-muted/40 border-[hsl(var(--border))] text-muted-foreground hover:border-brand-green/30"
                  )}
                >
                  <span>📝</span>
                  <span>Blank</span>
                </button>

                {ACTIVITY_TEMPLATES.map((tmpl) => {
                  const isSelected = selectedTemplateId === tmpl.id;
                  return (
                    <button
                      key={tmpl.id}
                      type="button"
                      onClick={() => handleSelectTemplate(tmpl)}
                      className={cn(
                        "px-3 py-1.5 rounded-xl border text-xs font-medium shrink-0 transition-all flex items-center gap-1.5",
                        isSelected
                          ? "bg-brand-mint border-brand-green text-brand-green-deep font-semibold shadow-xs ring-1 ring-brand-green/30"
                          : "bg-white border-[hsl(var(--border))] text-brand-green-deep/80 hover:bg-brand-mint/20 hover:border-brand-green/30"
                      )}
                    >
                      <span>{tmpl.emoji}</span>
                      <span>{tmpl.shortLabel}</span>
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* Notes — serif warm textarea + AI Auto-Analyze button */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label
                htmlFor="notes"
                className="text-sm font-medium text-brand-green-deep"
              >
                What happened? <span className="text-destructive">*</span>
              </Label>
              {!selectedTemplateId && (
                <button
                  type="button"
                  onClick={handleAutoAnalyze}
                  disabled={analyzing || !notes.trim()}
                  className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand-green hover:text-brand-green-deep disabled:opacity-50 transition-colors bg-brand-mint/60 hover:bg-brand-mint px-2.5 py-1 rounded-lg"
                  title="Automatically detects subject, moment, title, tags, and curriculum skills from notes"
                >
                  {analyzing ? (
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  ) : (
                    <Sparkles className="w-3.5 h-3.5 text-amber-500" />
                  )}
                  <span>{analyzing ? "Analyzing…" : "Auto-Fill with AI"}</span>
                </button>
              )}
              </div>

            <textarea
              ref={textareaRef}
              id="notes"
              rows={4}
              placeholder={
                activeTemplate?.placeholder ??
                "Write about today's learning, discoveries, field trips, or breakthrough moments…"
              }
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full px-4 py-3 rounded-xl border border-[hsl(var(--border))] text-[15px] leading-relaxed resize-none focus:outline-none focus:ring-2 focus:ring-brand-green/30 focus:border-brand-green placeholder:text-muted-foreground/60"
              style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
            />

            {/* Guided Prompt Chips */}
            {activeTemplate && activeTemplate.prompts.length > 0 && (
              <div className="pt-1 space-y-1">
                <p className="text-[11px] font-medium text-muted-foreground flex items-center gap-1">
                  <HelpCircle className="w-3 h-3 text-brand-green" />
                  <span>Tap a guiding question to add to your notes:</span>
                </p>
                <div className="flex flex-wrap gap-1.5">
                  {activeTemplate.prompts.map((p, i) => (
                    <button
                      key={i}
                      type="button"
                      onClick={() => handleInsertPrompt(p)}
                      className="inline-flex items-center gap-1 text-[11px] bg-muted/70 hover:bg-brand-mint text-brand-green-deep px-2.5 py-1 rounded-lg border border-transparent hover:border-brand-green/20 transition-colors text-left"
                    >
                      <Plus className="w-2.5 h-2.5 text-brand-green shrink-0" />
                      <span>{p}</span>
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* AI Curriculum Analysis Results Box */}
          {(suggestedSkills.length > 0 || learningSummary) && (
            <div className="bg-brand-mint/40 border border-brand-green/20 rounded-xl p-3 space-y-2 animate-in fade-in slide-in-from-top-1 duration-200">
              <div className="flex items-center gap-1.5 text-xs font-semibold text-brand-green-deep">
                <Sparkles className="w-3.5 h-3.5 text-amber-500" />
                <span>AI Curriculum Insights</span>
              </div>
              {learningSummary && (
                <p className="text-xs text-brand-green-deep/90 leading-relaxed italic bg-white/70 rounded-lg p-2 border border-brand-green/10">
                  &ldquo;{learningSummary}&rdquo;
                </p>
              )}
              {suggestedSkills.length > 0 && (
                <div className="space-y-1.5 pt-0.5">
                  <p className="text-[11px] font-semibold text-brand-green-deep/80 uppercase tracking-wide">
                    Identified Skills & Objectives:
                  </p>
                  <div className="flex flex-wrap gap-1.5">
                    {suggestedSkills.map((skill, i) => (
                      <span
                        key={i}
                        className="inline-flex items-center gap-1 text-xs bg-white border border-brand-green/30 text-brand-green-deep px-2.5 py-1 rounded-lg font-medium shadow-xs"
                      >
                        <CheckCircle2 className="w-3 h-3 text-brand-green shrink-0" />
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Subject grid */}
          <div className="space-y-1.5">
            <Label className="text-xs font-semibold text-brand-green-deep uppercase tracking-wider">
              Subject <span className="text-muted-foreground font-normal normal-case">(optional)</span>
            </Label>
            <div className="grid grid-cols-3 sm:grid-cols-4 gap-1.5">
              {SUBJECTS.map((s) => (
                <button
                  key={s.label}
                  type="button"
                  onClick={() => setSubject(subject === s.label ? "" : s.label)}
                  className={cn(
                    "flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl border text-left text-xs transition-all",
                    subject === s.label
                      ? "bg-brand-mint border-brand-green text-brand-green-deep font-semibold"
                      : "bg-white border-[hsl(var(--border))] text-muted-foreground hover:border-brand-green/30 hover:bg-brand-mint/20"
                  )}
                >
                  <span className="text-sm shrink-0">{s.emoji}</span>
                  <span className="truncate">{s.label}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Moment type */}
          <div className="space-y-1.5">
            <Label className="text-xs font-semibold text-brand-green-deep uppercase tracking-wider">
              Moment Type
            </Label>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-1.5">
              {MOMENTS.map((m) => (
                <button
                  key={m.value}
                  type="button"
                  onClick={() => setMoment(m.value)}
                  className={cn(
                    "flex items-center gap-1.5 px-2.5 py-2 rounded-xl border text-left text-xs transition-all",
                    moment === m.value
                      ? "bg-brand-mint border-brand-green text-brand-green-deep font-semibold"
                      : "bg-white border-[hsl(var(--border))] text-muted-foreground hover:border-brand-green/30 hover:bg-brand-mint/20"
                  )}
                >
                  <span>{m.emoji}</span>
                  <span className="truncate">{m.label}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Learning Duration (mins) */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label
                htmlFor="duration"
                className="text-xs font-semibold text-brand-green-deep uppercase tracking-wider flex items-center gap-1"
              >
                <Clock className="w-3.5 h-3.5 text-muted-foreground" />
                <span>Learning Time</span>
                <span className="text-muted-foreground font-normal lowercase">(syncs to progress)</span>
              </Label>
              {durationMins && parseInt(durationMins, 10) > 0 && (
                <span className="text-xs font-semibold text-brand-green">
                  {durationMins} mins
                </span>
              )}
            </div>
            <div className="flex items-center gap-1.5 flex-wrap">
              {DURATION_PRESETS.map((m) => (
                <button
                  key={m}
                  type="button"
                  onClick={() =>
                    setDurationMins(durationMins === String(m) ? "" : String(m))
                  }
                  className={cn(
                    "px-2.5 py-1 rounded-xl border text-xs font-medium transition-all",
                    durationMins === String(m)
                      ? "bg-brand-mint border-brand-green text-brand-green-deep font-bold"
                      : "bg-white border-[hsl(var(--border))] text-muted-foreground hover:border-brand-green/30"
                  )}
                >
                  {m}m
                </button>
              ))}
              <div className="flex-1 min-w-[100px]">
                <Input
                  id="duration"
                  type="number"
                  min="1"
                  max="720"
                  placeholder="Custom mins"
                  value={durationMins}
                  onChange={(e) => setDurationMins(e.target.value)}
                  className="h-7 text-xs rounded-xl"
                />
              </div>
            </div>
          </div>

          {/* Title + Date */}
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label
                htmlFor="title"
                className="text-xs font-semibold text-brand-green-deep uppercase tracking-wider"
              >
                Title <span className="text-muted-foreground font-normal normal-case">(optional)</span>
              </Label>
              <Input
                id="title"
                placeholder={activeTemplate?.defaultTitle ?? "e.g. Volcano experiment"}
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="rounded-xl h-9 text-xs"
              />
            </div>
            <div className="space-y-1">
              <Label
                htmlFor="edate"
                className="text-xs font-semibold text-brand-green-deep uppercase tracking-wider"
              >
                Date
              </Label>
              <Input
                id="edate"
                type="date"
                value={entryDate}
                onChange={(e) => setEntryDate(e.target.value)}
                className="rounded-xl h-9 text-xs"
              />
            </div>
          </div>

          {/* Photo upload */}
          <div className="space-y-1.5">
            <Label className="text-xs font-semibold text-brand-green-deep uppercase tracking-wider">
              Photo Evidence <span className="text-muted-foreground font-normal normal-case">(optional)</span>
            </Label>
            {photoUrl ? (
              <div className="relative w-full h-36 rounded-xl overflow-hidden border border-brand-green/20">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={photoUrl}
                  alt="Entry photo"
                  className="w-full h-full object-cover"
                />
                <button
                  type="button"
                  onClick={() => setPhotoUrl(null)}
                  className="absolute top-2 right-2 w-6 h-6 rounded-full bg-black/60 flex items-center justify-center hover:bg-black/80 transition-colors"
                >
                  <X className="w-3.5 h-3.5 text-white" />
                </button>
              </div>
            ) : (
              <button
                type="button"
                onClick={() => fileRef.current?.click()}
                disabled={uploadLoading}
                className="w-full h-20 rounded-xl border-2 border-dashed border-[hsl(var(--border))] flex flex-col items-center justify-center gap-1 text-muted-foreground hover:border-brand-green/40 hover:bg-brand-mint/10 transition-colors disabled:opacity-50"
              >
                {uploadLoading ? (
                  <Loader2 className="w-4 h-4 animate-spin text-brand-green" />
                ) : (
                  <Camera className="w-4 h-4 text-brand-green" />
                )}
                <span className="text-xs">
                  {uploadLoading ? "Uploading photo…" : "Tap to add a photo or keepsake"}
                </span>
              </button>
            )}
            <input
              ref={fileRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={handlePhotoChange}
            />
          </div>

          {/* Bloom Star Reward Hint */}
          <div className="flex items-center justify-between px-3.5 py-2 bg-amber-50/80 border border-amber-200/60 rounded-xl text-xs text-amber-800">
            <div className="flex items-center gap-1.5">
              <Star className="w-4 h-4 fill-amber-400 text-amber-500 shrink-0" />
              <span>
                {photoUrl
                  ? "+2 Bloom Stars (photo attached!)"
                  : "+1 Bloom Star (+2 with photo attached)"}
              </span>
            </div>
            <span className="text-[10px] font-semibold text-amber-700 bg-amber-100/80 px-2 py-0.5 rounded-full">
              Bloom Garden
            </span>
          </div>

          {error && (
            <p className="text-xs text-destructive bg-destructive/10 px-3 py-2 rounded-xl">
              {error}
            </p>
          )}

          <Button
            type="submit"
            className="w-full bg-brand-green hover:bg-brand-green-deep gap-2 font-semibold"
            disabled={loading}
          >
            {loading && <Loader2 className="w-4 h-4 animate-spin" />}
            {loading ? "Saving…" : "Save entry"}
          </Button>
        </form>
      </div>
    </div>
  );
}
