export interface ActivityTemplate {
  id: string;
  label: string;
  shortLabel: string;
  emoji: string;
  subject: string;
  moment: "REGULAR" | "BREAKTHROUGH" | "DAY_OUT" | "CREATIVE" | "SPECIAL";
  defaultDurationMins: number;
  defaultTags: string[];
  suggestedTags: string[];
  prompts: string[];
  placeholder: string;
  defaultTitle: string;
  description: string;
}

export const ACTIVITY_TEMPLATES: ActivityTemplate[] = [
  {
    id: "nature-walk",
    label: "Nature Walk & Outdoor Study",
    shortLabel: "Nature Walk",
    emoji: "🌲",
    subject: "Science",
    moment: "DAY_OUT",
    defaultDurationMins: 60,
    defaultTags: ["nature", "outdoors", "biology"],
    suggestedTags: [
      "nature",
      "outdoors",
      "biology",
      "wildlife",
      "habitats",
      "weather",
      "foraging",
      "plants",
    ],
    prompts: [
      "What plants, animals, or mini-beasts did they observe?",
      "What weather, terrain, or seasonal changes did you notice?",
      "What questions or discoveries sparked their curiosity?",
    ],
    placeholder:
      "Where did you go? What living things did they observe, collect, or ask questions about?",
    defaultTitle: "Nature walk & outdoor exploration",
    description: "Park walks, forest trails, pond dipping, birdwatching, and nature study.",
  },
  {
    id: "museum-trip",
    label: "Museum & Heritage Field Trip",
    shortLabel: "Museum Trip",
    emoji: "🏛️",
    subject: "History",
    moment: "DAY_OUT",
    defaultDurationMins: 120,
    defaultTags: ["field-trip", "history", "museum"],
    suggestedTags: [
      "field-trip",
      "history",
      "museum",
      "culture",
      "artefacts",
      "science-centre",
      "hands-on",
    ],
    prompts: [
      "Which gallery, artefact, or exhibit caught their attention?",
      "What surprising historical or scientific fact did they learn?",
      "What connections did they make to prior learning?",
    ],
    placeholder:
      "Which museum or heritage site did you visit? What exhibits and facts captured their interest?",
    defaultTitle: "Museum & heritage field trip",
    description: "Science museums, historical sites, galleries, castles, and cultural exhibits.",
  },
  {
    id: "cooking-baking",
    label: "Cooking & Baking (Life Skills)",
    shortLabel: "Cooking & Baking",
    emoji: "🍳",
    subject: "Maths",
    moment: "CREATIVE",
    defaultDurationMins: 45,
    defaultTags: ["cooking", "life-skills", "practical-maths"],
    suggestedTags: [
      "cooking",
      "baking",
      "life-skills",
      "practical-maths",
      "measuring",
      "fractions",
      "chemistry",
      "food-hygiene",
    ],
    prompts: [
      "What recipe or dish did you prepare together?",
      "What measurements, weights, or fractions did they practice?",
      "What safety, hygiene, or chemical transformations did you discuss?",
    ],
    placeholder:
      "What did you make? How did they measure ingredients, follow steps, or learn about heat and food?",
    defaultTitle: "Cooking & practical kitchen maths",
    description: "Measuring ingredients, following recipes, nutrition, and kitchen chemistry.",
  },
  {
    id: "sports-pe",
    label: "Sports, PE & Physical Movement",
    shortLabel: "Sports & PE",
    emoji: "⚽",
    subject: "PE",
    moment: "REGULAR",
    defaultDurationMins: 60,
    defaultTags: ["sports", "fitness", "pe"],
    suggestedTags: [
      "sports",
      "fitness",
      "pe",
      "teamwork",
      "coordination",
      "swimming",
      "cycling",
      "gymnastics",
    ],
    prompts: [
      "What sport, drill, or physical movement did they focus on?",
      "What motor skill, stamina, or balance improvement did you notice?",
      "How did they show perseverance, teamwork, or sportsmanship?",
    ],
    placeholder:
      "What activity or sports club took place? How did they perform, coordinate, or improve?",
    defaultTitle: "PE & sports movement session",
    description: "Swimming, football, martial arts, gymnastics, cycling, athletics, and active games.",
  },
  {
    id: "arts-crafts",
    label: "Arts, Crafts & Model Making",
    shortLabel: "Arts & Crafts",
    emoji: "🎨",
    subject: "Art",
    moment: "CREATIVE",
    defaultDurationMins: 45,
    defaultTags: ["art", "craft", "creativity"],
    suggestedTags: [
      "art",
      "craft",
      "creativity",
      "fine-motor",
      "painting",
      "sculpture",
      "sewing",
      "design",
    ],
    prompts: [
      "What artwork, model, or craft did they design and create?",
      "What media or techniques were used (e.g. watercolour, clay, collage)?",
      "What inspired their theme, colour choices, or composition?",
    ],
    placeholder:
      "What did they create? What materials, tools, and creative choices did they use?",
    defaultTitle: "Art & creative craft project",
    description: "Painting, sketching, clay modelling, woodworking, sewing, and mixed media.",
  },
  {
    id: "science-experiment",
    label: "DIY Science Experiment",
    shortLabel: "Science Experiment",
    emoji: "🔬",
    subject: "Science",
    moment: "BREAKTHROUGH",
    defaultDurationMins: 45,
    defaultTags: ["science", "stem", "experiment"],
    suggestedTags: [
      "science",
      "stem",
      "experiment",
      "hypothesis",
      "hands-on",
      "physics",
      "chemistry",
      "investigation",
    ],
    prompts: [
      "What scientific question or hypothesis did you test?",
      "What materials were used and what steps did they conduct?",
      "What were the results, and did they match the prediction?",
    ],
    placeholder:
      "What experiment did you run? What was the hypothesis, observation, and key takeaway?",
    defaultTitle: "Hands-on science investigation",
    description: "Home chemistry, physics tests, optics, circuit building, and STEM experiments.",
  },
  {
    id: "library-reading",
    label: "Library Visit & Free Reading",
    shortLabel: "Library & Reading",
    emoji: "📚",
    subject: "English",
    moment: "REGULAR",
    defaultDurationMins: 45,
    defaultTags: ["reading", "literacy", "library"],
    suggestedTags: [
      "reading",
      "literacy",
      "library",
      "books",
      "storytelling",
      "comprehension",
      "vocabulary",
      "research",
    ],
    prompts: [
      "What books, genres, or research topics did they explore?",
      "Did you read aloud, read independently, or discuss vocabulary?",
      "What was their favourite character, fact, or story development?",
    ],
    placeholder:
      "Which books or topics were read? What new words or plot ideas did you discuss?",
    defaultTitle: "Library visit & independent reading",
    description: "Library trips, audiobooks, shared reading, poetry, and research browsing.",
  },
  {
    id: "real-world-maths",
    label: "Real-World Maths & Money",
    shortLabel: "Money & Maths",
    emoji: "🛒",
    subject: "Maths",
    moment: "REGULAR",
    defaultDurationMins: 30,
    defaultTags: ["real-world-maths", "money", "practical-maths"],
    suggestedTags: [
      "real-world-maths",
      "money",
      "budgeting",
      "practical-maths",
      "shopping",
      "estimating",
      "time-management",
      "board-games",
    ],
    prompts: [
      "What real-world situation did you practice (e.g. shopping, budgeting, board games)?",
      "How did they estimate prices, compare values, or count change?",
      "What mental maths or problem-solving strategy did they apply?",
    ],
    placeholder:
      "How did you use maths in real life today (e.g. grocery budgeting, board game strategy, timing)?",
    defaultTitle: "Real-world maths & financial literacy",
    description: "Supermarket shopping, budgeting, calculating discounts, board games, and practical estimation.",
  },
  {
    id: "gardening-botany",
    label: "Gardening, Plants & Botany",
    shortLabel: "Gardening & Botany",
    emoji: "🌱",
    subject: "Science",
    moment: "CREATIVE",
    defaultDurationMins: 45,
    defaultTags: ["gardening", "botany", "plants"],
    suggestedTags: [
      "gardening",
      "botany",
      "plants",
      "nature",
      "life-cycles",
      "photosynthesis",
      "soil",
      "sustainability",
    ],
    prompts: [
      "What seeds, seedlings, or plants did you plant or maintain?",
      "What plant anatomy, soil, sunlight, or water needs did you discuss?",
      "What progress or changes have occurred since last time?",
    ],
    placeholder:
      "What garden work was done? What did they learn about seeds, soil, sunlight, or growth?",
    defaultTitle: "Gardening & plant study session",
    description: "Planting seeds, tending flowerbeds, harvesting vegetables, and composting.",
  },
  {
    id: "community-faith",
    label: "Community, Faith & Volunteering",
    shortLabel: "Community & Faith",
    emoji: "🌙",
    subject: "Islamic Studies",
    moment: "SPECIAL",
    defaultDurationMins: 60,
    defaultTags: ["community", "values", "faith"],
    suggestedTags: [
      "community",
      "values",
      "faith",
      "charity",
      "volunteering",
      "ethics",
      "citizenship",
      "kindness",
    ],
    prompts: [
      "What community event, charity act, or faith gathering took place?",
      "What discussion did you have about empathy, values, or gratitude?",
      "How did they actively participate or help others?",
    ],
    placeholder:
      "What community or faith activity took place? What ethical lessons or empathy did it encourage?",
    defaultTitle: "Community, values & faith activity",
    description: "Charity initiatives, community group meetups, mosque/church events, and volunteering.",
  },
];
